import React from "react";
import './style.scss';
import '../../../assets/styles/style.css';

const TermsCondition = () => {
  return (
    <div className="content" style={{ margin: '2rem 0rem' }}>
      <section className="terms-condition">
        <div className="container-fluid">
          <div className="row">
            <div className="col">
              <h2>Terms of Use</h2>
              <p>This end user agreement (the "Agreement") should be read by you (the "User" or "you") in its entirety prior to your use of GADA's service or products. Be aware that this Agreement constitutes a legally binding agreement between you and GADA (referred to herein as "GADA", "us" or "we") which owns and operates <a href="https://www.gada.finance/">www.gada.finance</a>, GADA Light and GADA Pro applications, herein all called by GADA platforms, and its services (the "Service"). You consent to adhering to all the terms set forth in this Agreement when/if you are provided with an “I Agree” button and clicking on it. </p>
              <h3>1. Grant of License</h3>
              <p>1.1. GADA platforms grants the User a non-exclusive, personal, non-transferable right to use the Service on your personal computer or other device that accesses the Internet in order to access and use the services available and described on the GADA platforms websites (the website and all its functionality together being the "Service"), subject to the terms and conditions contained herein.</p>
              <p>1.2. The Service is not for use by (i) minors and individuals under the age of 18 years, (ii) individuals who can be considered minors or under the age of majority adulthood in their specific jurisdiction(s) (iii) individuals accessing or using the Service from any jurisdiction in which it is illegal to do so. GADA does not have the ability to verify the legality of the Service in every jurisdiction, therefore it is entirely up to the User to determine whether or not their use of the Service is lawful. </p>
              <p>1.3. GADA and its licensors are the sole holders of all rights in and to the Service and code, technology, organization and structure, architecture, including copyright, trade secrets, intellectual property and other rights. You may not: (a) copy, create derivative works, distribute, publish, reverse engineer, decompile, disassemble, modify, or translate the GADA platforms or the Service; or (b) use the Service that in any way is prohibited by applicable laws or regulations (each of the above herein defined as an "Unauthorized Use"). </p>
              <p>1.4 GADA reserves any and all rights implied or otherwise, which are not expressly granted to the User hereunder and retain all rights, title and interest in and to the Service. You agree that you will be solely liable for any damage, costs or expenses arising out of or in connection with the commission by you of any Unauthorized Use. You shall notify GADA immediately upon becoming aware of the commission by any person of any Unauthorized Use and shall provide GADA with reasonable assistance with any investigations it conducts in light of the information provided by you in this respect.</p>
              <p>1.5. The term "GADA", “GADA LIGHT” and “GADA PRO”, its domain names and any other trade marks, or service marks used by GADA as part of the Service (the "Trade Marks"), are solely owned by GADA. In addition, all content on the website, including, but not limited to, the images, pictures, graphics, photographs, animations, videos, music, audio and text (the "Site Content") belongs to GADA and is protected by copyright and/or other intellectual property or other rights. You hereby acknowledge that by using the Service, you obtain no rights in the Site Content and/or the Trade Marks, or any part thereof. Under no circumstances may you use the Site Content and/or the Trade Marks without GADA's prior written consent. Additionally, you agree not to do anything that will harm or potentially harm the rights, including the intellectual property rights of GADA.</p>
              <h3>2. No Warranties</h3>
              <p>2.1. GADA disclaims any and all warranties, expressed or implied, in connection with the service which is provided to you "as is" and we provide you with no warranty or representation whatsoever regarding its quality, fitness for purpose, completeness or accuracy.</p>
              <p> 2.2. Regardless of GADA's efforts, GADA makes no warranty that the service will be uninterrupted, timely or error-free, or that defects will be corrected.</p>
              <h3>3. Authority/Terms of Service</h3>
              <p>You agree to the rules of the Service provided and described on the GADA platforms. GADA retains all authority over the issuing, maintenance, and closing of the Service. The decision of GADA's management, concerning any use of the Service, or dispute resolution, is final and shall not be open to review or appeal.</p>
              <h3>4. Your Representations and Warranties</h3>
              <p>Prior to your use of the Service and on an ongoing basis you represent, warrant, covenant and agree that:</p>
              <p> 4.1. there is a risk of losing cryptocurrency & other funds of value when using the Service and GADA has no responsibility to you for any such loss;</p>
              <p> 4.2. your use of the Service is at your sole option, discretion and risk;</p>
              <p> 4.3. you are solely responsible for any applicable taxes which may be payable on cryptocurrency traded or transacted by you through your using the Service;</p>
              <p> 4.5. the telecommunications networks, blockchain networks (such as Cardano, Ethereum and Binance Smart Chain) and Internet access services required for you to access and use the Service are entirely beyond the control of GADA and GADA platforms shall have no liability whatsoever for any outages, slowness, capacity constraints or other deficiencies affecting the same; and</p>
              <p> 4.6. you are (i) aged 18 or over, (ii) you are of the age of majority in your jurisdiction, (iii) you are accessing the Service from a jurisdiction in which it is legal to do so, (iv) you are not a Politically Exposed Person (PEP) nor are you on any U.S. or EU Sanctions lists or terrorism finance watchlists, and (v) that you will inform GADA immediately if you enter onto one of these lists or change your residence to a prohibited jurisdiction.</p>
              <p> 4.7 You warrant that should you discover a bug or error that may lead to an exploit of the Service or other loss of funds from GADA, you have the responsibility to notify GADA at support@gada.finance in a timely manner. Furthermore, any attempt by you to use such a discovered exploit or bug for illicit financial gain is illegal and strictly prohibited under this Agreement. GADA reserves the right to prosecute to the fullest extent of the law anyone who exploits or attempts to exploit the Service in an unlawful manner. Such exploits or bugs should be disclosed in a responsible manner and in strict confidence with support@gada.finance and no other entity. </p>
              <h3>5. Prohibited Uses</h3>
              <p>5.1. PERSONAL USE. The Service is intended solely for the User’s personal use. The User is only allowed to use the Service for personal use, and may not create multiple accounts, including for the purpose of collusion and/or abuse of service.</p>
              <p> 5.2 EXPLOITS & BUGS. The Service is provided as is, and any exploitation of the Service or errors in program logic and/or code (bugs) constitutes a Prohibited Use and a material breach of this Agreement. Any funds the user may misappropriate in this manner pursuant to this clause shall be considered void and the immediate property of GADA, without limit. </p>
              <p> 5.3 JURISDICTIONS. Persons located in or residents of the United States, North Korea, Iran, Venezuela or any other jurisdiction in which it is prohibited from using the Service (the ”Prohibited Jurisdictions”) are not permitted to make use of the Service. For the avoidance of doubt, the foregoing restrictions on Service from Prohibited Jurisdictions applies equally to residents and citizens of other nations while located in a Prohibited Jurisdiction. Any attempt to circumvent the restrictions on usage by any persons located in a Prohibited Jurisdiction or Restricted Jurisdiction, is a breach of this Agreement. An attempt at circumvention includes, but is not limited to, manipulating the information used by GADA to identify your location and providing GADA with false or misleading information regarding your location or place of residence.
                Any and all monies (including cryptocurrencies) of a person located in a Prohibited Jurisdiction on the Service are VOID, and can be confiscated or may be returned to the person at GADA's sole discretion.</p>
              <h3>6. Know your Customer (“KYC”) and Anti-Money Laundering (AML) Policy</h3>
              <p>GADA is a permissionless and fully decentralised platform for token sales, swaps, and decentralized exchange. As a software development company, GADA has no role in enforcing KYC by default, however we do provide such tools for fundraising entities using GADA platforms to enforce on their users, if the entities choose to do so. The use of KYC/AML tools on GADA by fundraising entities using the Service is completely at the discretion of said entities.</p>
              <p> Although GADA makes no warranty as to the merit, legality or juridical nature of any token (including whether or not it is considered a security or financial instrument under any applicable Securities Laws), token sale or fundraiser on top of GADA, we nonetheless understand the need of some token projects to require KYC/AML on their token sale participants.</p>
              <p> Therefore, and at the sole behest of fundraising entities and/or competent regulatory authorities:</p>
              <p> GADA reserves the right, at any time, to ask for any KYC documentation it deems necessary to determine the identity and location of a User. GADA reserves the right to restrict service and payment until identity is sufficiently determined.</p>
              <p> GADA further reserves the right to share submitted KYC information and documentation to 3rd parties to verify the authenticity of submitted information, and the end user (you) agree to this by using the Service. </p>
              <p> GADA reserves the right to confiscate any and all funds that are found to be in violation of relevant and applicable anti-money laundering (AML) and countering terrorism financing (CFT) laws and regulations, and to cooperate with the competent authorities when and if necessary. </p>
              <h4>AML & SANCTIONS COMPLIANCE. </h4>
              <p>GADA expressly prohibits and rejects the use of the Service for any form of illicit activity, including money laundering, terrorist financing or trade sanctions violations, consistent with various jurisdictions’ laws, regulations and norms. To that end, the Service is not offered to individuals or entities on any Politically Exposed Persons (PEP) lists, or subject to any United States, European Union, or other global sanctions or watch lists. By using the Service, end users represent and warrant that they are not on any such lists. </p>
              <h3>7. Breach</h3>
              <p>7.1. Without prejudice to any other rights, if a User breaches in whole or in part any provision contained herein, GADA reserves the right to take such action as it sees fit, including terminating this Agreement or any other agreement in place with the User and/or taking legal action against such User.</p>
              <p>7.2. You agree to fully indemnify, defend and hold harmless GADA and its shareholders, directors, agents and employees from and against all claims, demands, liabilities, damages, losses, costs and expenses, including legal fees and any other charges whatsoever, howsoever caused, that may arise as a result of: (i) your breach of this Agreement, in whole or in part; (ii) violation by you of any law or any third party rights; and (iii) use by you of the Service. </p>
              <h3>8. Limitations and Liability</h3>
              <p>8.1. Under no circumstances, including negligence, shall GADA be liable for any special, incidental, direct, indirect or consequential damages whatsoever (including, without limitation, damages for loss of business profits, business interruption, loss of business information, or any other pecuniary loss) arising out of the use (or misuse) of the Service even if GADA had prior knowledge of the possibility of such damages.</p>
              <p>8.2. Nothing in this Agreement shall exclude or limit GADA's liability for death or personal injury resulting from its negligence.</p>
              <h3>9. Disputes</h3>
              <p>If a User wishes to make a complaint, please contact GADA's customer service team at Support@gada.finance. Should any dispute not be resolved to your satisfaction you may pursue remedies in the governing law jurisdiction set forth below.</p>
              <h3>10. Amendment</h3>
              <p>GADA reserves the right to update or modify this Agreement or any part thereof at any time or otherwise change the Service without notice and you will be bound by such amended Agreement upon posting. Therefore, we encourage you to check the terms and conditions contained in the version of the Agreement in force at such time. Your continued use of the Service shall be deemed to attest to your agreement to any amendments to the Agreement.</p>
              <h3>11. Governing Law</h3>
              <p>The Agreement and any matters relating hereto shall be governed by, and construed in accordance with, the laws of the British Virgin Islands. You irrevocably agree that, subject as provided below, the courts of the British Virgin Islands shall have exclusive jurisdiction in relation to any claim, dispute or difference concerning the Agreement and any matter arising therefrom and irrevocably waive any right that it may have to object to an action being brought in those courts, or to claim that the action has been brought in an inconvenient forum, or that those courts do not have jurisdiction. Nothing in this clause shall limit the right of GADA to take proceedings against you in any other court of competent jurisdiction, nor shall the taking of proceedings in any one or more jurisdictions preclude the taking of proceedings in any other jurisdictions, whether concurrently or not, to the extent permitted by the law of such other jurisdiction.</p>
              <h3>12. Severability</h3>
              <p>If a provision of this Agreement is or becomes illegal, invalid or unenforceable in any jurisdiction, that shall not affect the validity or enforceability in that jurisdiction of any other provision hereof or the validity or enforceability in other jurisdictions of that or any other provision hereof.</p>
              <h3>13. Assignment</h3>
              <p>GADA reserves the right to assign this agreement, in whole or in part, at any time without notice. The User may not assign any of his/her rights or obligations under this Agreement.</p>
              <h3>14. Miscellaneous</h3>
              <p>14.1. No waiver by GADA of any breach of any provision of this Agreement (including the failure of GADA to require strict and literal performance of or compliance with any provision of this Agreement) shall in any way be construed as a waiver of any subsequent breach of such provision or of any breach of any other provision of this Agreement.</p>
              <p>14.2. Nothing in this Agreement shall create or confer any rights or other benefits in favour of any third parties not party to this Agreement.</p>
              <p>14.3. Nothing in this Agreement shall create or be deemed to create a partnership, agency, trust arrangement, fiduciary relationship or joint venture between you and GADA.</p>
              <p>14.4. GADA may assign, transfer, charge, sub-license, or deal in any other manner with this Agreement, or sub-contract any of its rights and obligations under this Agreement, to any other party.</p>
              <p>14.5. This Agreement constitutes the entire understanding and agreement between you and GADA regarding the Service and supersedes any prior agreement, understanding, or arrangement between you and GADA.</p>
              <h3>15. Cryptocurrency</h3>
              <p>CRYPTOCURRENCY VALUES CAN FLUCTUATE GREATLY IN VALUE DEPENDING ON MARKET CONDITIONS.
                THE USER WARRANTS THAT IT IS AWARE OF THE VOLATILE NATURE OF CRYPTOCURRENCIES, AND HOLDS GADA HARMLESS FOR ANY LOSS OR DAMAGES ARISING FROM SUCH VOLATILITY</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default TermsCondition;
